name: mrtgrady1
favicon: null
layout_spectrum: 0.4821
typography_spectrum: 0.8985906920861453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.21380413766019046
  lightness: 0.8515601537656039
  saturation: 0.5626733237877488
  rhythmicContrast: 0.7396773344371468
purpose: []
